---
abstract: 'Calendar view'
author:
  - 'Best Practical Solutions'
  - 'Nicolas Chuche <nchuche@barna.be>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.12'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RTx-Calendar
no_index:
  directory:
    - html
    - inc
    - static
  package:
    - RT::Interface::Web::Menu
requires:
  Data::ICal: 0
  DateTime: 0
  DateTime::Set: 0
  Digest::SHA: 0
  perl: 5.8.3
resources:
  license: http://dev.perl.org/licenses/
version: '0.20'
x_module_install_rtx_version: '0.36'
x_requires_rt: 4.0.0
